nolanlawson/emoji-picker-element

README.md, docs/index.html
Related to #9, we should at least communicate this.
This adds a note to the demo page and to the README about Firefox private browsing.
=> docs: add warning about Firefox private browsing

src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js, test/spec/picker/Picker.test.js
fixes #14
I can't seem to find a solution that will work in Firefox or Safari on macOS, so for the time being I think it's better to just disable the `blur`/`focusout` event listener entirely. It's just a nice quality-of-life improvement when it works (i.e. focus elsewhere, the dropdown collapses), but it's not worth it if it completely breaks the behavior for mouse/trackpad users on macOS.
Let this also serve as a lesson to me that it's not good enough to test on 3 browsers on Ubuntu – I need to test on 3 browsers on 3 OSes! The joy of webdev. :joy:
=> fix: remove blur/focusout event for now

src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js, src/picker/styles/global.scss, test/spec/picker/Picker.test.js
fixes #16
I tested in all three engines in macOS and Ubuntu, as well as iOS Safari, macOS Safari VoiceOver, and NVDA Firefox on Windows. I tested blurring by clicking outside of the skin tone picker, as well as using both the mouse/touch and enter/spacebar to select the buttons. I learned a lot of somewhat arcane things about how browsers handle this stuff.
First off, `<button>`s behave differently in iOS Safari and Safari/Firefox on Mac. See https://stackoverflow.com/a/42764495/680742 and https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button#Clicking_and_focus and 
Second off, apparently the way buttons work is that Enter fires on keydown and spacebar fires on keyup. Because it wouldn't be the web if things weren't wildly unpredictable. :upside_down_face: …
=> fix: collapse skin tone picker on blur

src/picker/components/Picker/Picker.html, test/spec/picker/Picker.test.js
Just occurred to me that, when searching, these tabs should not be `aria-selected` because they don't have a visual indicator under them.
=> fix: tabs are not aria-selected in search mode

src/picker/components/Picker/Picker.html
aXe has a warning about the combobox, because the listbox is not a child of the combobox. I'm using `aria-controls`, but adding `aria-owns` fixes this.
In VoiceOver and NVDA, it seems to make no difference either way, but we might as well get rid of the warning.
=> fix: fix aXe warning about aria-owns

README.md, bin/generateTypeDocs.js, src/types/picker.ts, src/types/shared.ts
Forgot to add TypeScript annotations to indicate that you can set `customEmoji` on the picker as well as the database.
=> docs: fix typescript types for Picker's customEmoji

README.md, package.json, src/picker/PickerElement.js, src/types/picker.ts, test/spec/picker/attributes.test.js
This allows users to set the locale, data source, and skin tone emoji using HTML attributes as well as properties.
Fixes #7
=> feat: support attribute format for some properties

README.md, src/picker/components/Picker/Picker.js, src/types/picker.ts, src/types/shared.ts, test/spec/picker/Picker.test.js, test/spec/utils.js
Fixes #41
Adds the ability to define how you want custom categories to be sorted (default: alphabetical).
=> feat: add customCategorySort function

README.md, src/picker/components/Picker/Picker.js, src/types/picker.ts, src/types/shared.ts, test/spec/picker/Picker.test.js
Related to #41. I thought about it, and I like this name better.
MDN calls it a [compareFunction](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort), but I think `customCategoryCompareFunction` is too wordy. And yet, `sort` is weird because it's not a noun. `sorting` is slightly wordier, but feels better to me. Naming things is hard.
Not a breaking change because we haven't had a release yet.
=> fix: rename customCategorySort to customCategorySorting

src/picker/utils/testColorEmojiSupported.js
On Chrome on Mac, unsupported Emoji v13 emoji render as gray boxes. But when we do the support detection, we end up with `0,0,0,61` instead of the expected `0,0,0,0` for the image data, i.e. there's an alpha layer of 61. So we render gray boxes for Emoji v13. This fixes that.
=> fix: fix emoji support detection on Chrome on Mac

src/picker/utils/checkZwjSupport.js
On Windows, there are lots of emoji like :family: that are ~50% the size of the "baseline" emoji we use for testing for fake ZWJ emoji (like black cat = cat plus black rectangle). This fixes that by making the fudging logic a bit more forgiving.
I tested on more browsers and Oses than I'm comfortable admitting, and it seems to be working well. It also still works for weird cases like Epiphany Browser on Linux where the numbers are all slightly off one another by decimal places.
=> fix: fix ZWJ detection on windows

README.md
This is beneficial for folks who aren't using npm or just want to get started quickly. I like having some code examples you can just paste into an HTML file to get going.
=> docs: add docs on how to use as script tag

README.md, docs/index.html
=> docs: add docs on firefox private mode and IDB

package.json, yarn.lock
Seems it's safe to update typescript/typedoc but not yet typedoc-plugin-markdown since that changes the README file.
=> chore: update typescript/typedoc

src/picker/components/Picker/Picker.html
Dunno how I missed this, but the favorites bar was rendering custom emoji as `<img>`s whereas elsewhere it's a `<div>`. Should be consistent about this.
Also I tested `loading=lazy` but didn't really seem to work well in Chrome. Maybe worth re-evaluating now that Firefox has it too.
=> fix: use consistent HTML for custom emoji

src/picker/components/Picker/Picker.html
Testing in Chrome, this works quite well. As you scroll, custom emoji are loaded lazily.
In Firefox, it doesn't work well at all, but this is no worse than the status quo of loading all images eagerly at once. Probably FF needs to tweak their algorithm for inner scrollers as opposed to document scrollers.
Safari does not support this yet but it's behind a flag.
For the favorites bar it doesn't matter much since the favorites bar is always visible. But I keep it for consistency and because maybe people have the emoji-picker in a place where it's not immediately visible, so lazy-loading makes sense in that case.
=> perf: use lazy image loading

src/picker/components/Picker/Picker.html
There's no text or images inside of this node, so no need for aria-hidden.
=> fix: remove unnecessary aria-hidden

src/types/picker.ts
Good evening,
Some days ago I found out, that the picker types don't have a signature for `removeEventListener`, so I was about to create an issue. But then I though "Why don't you fix that?". Then I saw your types and the dummy classes and five shaved yaks later I'm here. (Yes I read the contribution guidelines.)
This PR:
- Converts all .ts files to .d.ts files and removes the dummy implementations.
- Gets rid of `@ts-ignore` 
- Changes the typedoc call to also include the .d.ts files
- Changes the generateTOC script, so it still finds the scripts
- Add signatures for removeEventListener
Feel free to review!
=> Convert .ts to .d.ts files

src/database/utils/requiredKeys.js
`emoticon` was never required. It's already listed in the `optionalKeys` in `trimEmojiData.js` anyway
=> fix: emoticon is not a required field

src/picker/components/Picker/Picker.js, test/spec/picker/custom.test.js
Not sure this is really testable, because it only manifests when IndexedDB takes a while to return. I think fakeIndexedDB just returns in the same turn of the event loop, so we may not be able to catch it. But in any case, this is the fix.
Fixes #84
=> fix: fix race condition on custom emoji

src/database/idbInterface.js, src/database/utils/normalizeTokens.js, src/database/utils/transformEmojiData.js, test/spec/database/getEmojiBySearchQuery.test.js, test/spec/database/getEmojiByShortcode.test.js
Fixes #88
The issue here is that shortcodes like `smiling_face_with_3_hearts` contain a short string, `3`, which is not indexed in the search tokens. We also have problems with shortcodes like `v` (:v:) where there are no usual shortcodes at all.
Of course the easiest solution here would be to create an IDB index on shortcodes. However, this seems like a wasteful use of disk space to me, as 1) `getEmojiByShortcode()` is not always used, and 2) all shortcodes become tokens that are indexed for searching anyway.
So I'm going to keep the current system of filtering the database using the shortcode broken up into search tokens, while also adding special cases for tokens like `3` or `v` (which requires a full database scan – reasonable IMO given that so few shortcodes are like this).
=> fix: fix short tokens in getEmojiByShortcode

package.json, src/database/idbInterface.js
Yet another alternative to #91 and #93. Just replaces the current single-item cursor with a batched cursor.
Perf improves from ~400ms to ~150ms using the benchmark described in the code comments, and nothing about the DB structure had to change. The code size did grow a slight amount.
=> perf: use batch cursor for full DB scan

src/database/idbInterface.js
I actually benchmarked this (https://github.com/nolanlawson/emoji-picker-element/tree/marks vs https://github.com/nolanlawson/emoji-picker-element/tree/optimize-favorites) and it turns out that in both Chrome and Firefox the difference is negligible (~30ms in Chrome on 6x slowdown, <10ms in Firefox), or there's even a small perf hit for parallelizing these two calls (~2ms in Chrome on 6x). So this comment can be replaced.
=> refactor: add clarifying code comment

package.json, src/picker/components/Picker/Picker.html
Simplifies some HTML that doesn't need to be so verbose, dropping the bundle size a bit.
=> perf: simplify baseline emoji html

src/database/idbInterface.js, test/spec/database/custom.test.js, test/spec/database/getEmojiByShortcode.test.js
fixes a bug in `getEmojiByShortcode` when native emoji don't have any shortcodes (e.g. English github shortcode set).
=> fix: fix getEmojiByShortcode when shortcodes are optional

package.json
Tests are failing in CI due to out of memory errors, apparently this helps: https://jestjs.io/docs/en/troubleshooting#tests-are-extremely-slow-on-docker-andor-continuous-integration-ci-server
=> chore: use jest --runInBand for better CircleCI perf

src/picker/components/Picker/Picker.js
Looks like JSDom fixed `getElementById` on a shadow root.
=> test: remove no-longer-needed jest-only code

README.md, bin/versionsAndTestEmoji.js, package.json, test/spec/database/Database.test.js, test/spec/database/getEmojiBySearchQuery.test.js, test/spec/picker/Picker.test.js, test/spec/picker/shared.js, yarn.lock
This, along with changes to emoji-picker-element-data to update from the upstream emojibase-data release, allows for emoji 13.1 support.
Related: #112
=> feat: support emoji 13.1

bin/versionsAndTestEmoji.js
There's no point in using the color test for 12.1 and 13.1 because these only contain compound emoji from previous versions.
=> fix: simplify emoji color check algorithm

README.md, package.json, src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.scss, src/picker/styles/global.scss, src/picker/styles/variables.scss
fixes #133
Adds two new CSS variables: `--category-emoji-padding` and `--category-emoji-size`. Both default to `--emoji-padding` and `--emoji-size`.
=> feat: allow styling category emoji separately

bin/generateCssDocs.js, custom-elements.json, package.json
Fixes #31
I think this is mostly aspirational, as it doesn't seem like this file format is supported out-of-the-box by VS Code or WebStorm, but [this post](https://dev.to/open-wc/introducing-custom-elements-manifest-gkk) convinced me to go ahead and add it. Maybe it will do something useful in the future!
If nothing else, if IDEs ever add support for this and I did something wrong, at least there is a file now that people can edit and open a PR to fix.
=> feat: add custom-elements.json

src/database/Database.js
Jest 27 was complaining about this code path never getting hit. From looking at the code, it seems indeed impossible for the `else` to ever get hit - the `ready()` function always ensures that `this._db` is set, and we `await` it. So it will definitely always return true.
Also this should only really matter if someone calls `db.close()` twice or `db.delete()` twice... which the tests already cover.
=> fix: remove unused code

test/spec/picker/constructor.test.js, test/spec/picker/dataSource.test.js, test/spec/shared.js
Adds a test for some Picker constructor options that I almost broke when trying to update Svelte.
=> test: add tests for various constructor options

rollup.config.js
Fixes a warning about how this option was forced to false.
=> fix: fix rollup compiler warning

.circleci/config.yml, README.md, config/jest.setup.js, package.json, src/picker/PickerElement.js, src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js, src/picker/utils/runAll.js, src/picker/utils/widthCalculator.js, test/spec/picker/lifecycle.test.js, yarn.lock
Incidentally this fixes #149.
TODO:
=>  fix: update svelte to 3.37.0

rollup.config.js
=> chore: only show rollup-plugin-analyzer on DEBUG=1

bin/versionsAndTestEmoji.js, src/picker/utils/determineEmojiSupportLevel.js
Theoretically it should be faster when testing emoji support to start with the latest (13.1) and work backwards, rather than starting with the oldest and working forward, because we can short-circuit if the latest (13.1) is supported, which should be the case in most modern browsers.
=> perf: determine emoji support in reverse order

src/picker/components/Picker/Picker.js
Fixes a bug that snuck in in 1.6.3 that causes an infinite requestAnimationFrame loop due to Svelte invalidations.
=> fix: fix tabPanel scrollTop bug

src/picker/PickerElement.js
After reading https://eslint.org/docs/rules/no-prototype-builtins, I realized I was doing this slightly wrong. Although it probably doesn't matter, and it's probably safe to use `this.hasOwnProperty`. But I guess to play it safe I'll abide by the rule.
=> fix: use Object.prototype.hasOwnProperty

README.md
Closes #183 
Rather than #187 I'd rather just add some docs demonstrating how to use `emoji-picker-element` in React. Maintaining our own React wrapper is too much work IMO. React should improve their custom element integration.
=> docs: add docs for react

.gitignore, README.md, bin/buildI18n.js, package.json, src/picker/PickerElement.js, src/picker/i18n/de.js, src/picker/i18n/fr.js
Adds built-in translations for French and German based on https://github.com/nolanlawson/pinafore/commit/a028a7e880b9bb98ecabb0dd3ece2fc6a38e58f7 and https://github.com/nolanlawson/pinafore/commit/96d84134b477beb203ddde82697dee4d577dbba5
Also adds a concept of built-in translations so that people can use the provided translations.
Related: #188
=> feat: add built-in translations

src/database/idbInterface.js, src/database/idbUtil.js
There's no need to do separate `objectStore.delete()`s when we can just call `objectStore.clear()`.
=> perf: use IDBObjectStore.clear

src/picker/components/Picker/Picker.js, test/spec/picker/favorites.test.js
Fixes #205
I can't really think of a strong reason to update the favorites immediately. The favorites are an enhancement; they aren't a critical part of the experience. And it's confusing to see them move around.
If people want these to update, they can create a new `<emoji-picker>` element or remove it from the DOM and re-insert it into the DOM. This seems reasonable to me as most pickers I imagine will be created on-demand and dismissed as soon as the user picks an emoji. If not, the favorites will update when the page is refreshed.
=> fix: update favorites only on mount

src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js
Testing on Chrome 92 on a Nexus 5, I don't see any framerate issues in this animation anymore, even when using the percent-based animation. It looks like whatever the perf bug was, Chrome fixed it.
=> perf: remove pixel-based indicator animation

src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js, src/picker/styles/picker.scss, test/adhoc/index.html
fixes #212
I'm not sure if I'm ready to merge this yet. I'm using CSS logical properties, which is still not supported in old versions of iOS: https://caniuse.com/css-logical-props
I'm trying to think if there's a good workaround that doesn't involve a lot of gymnastics. Slight differences in padding/margin are fine in my opinion, but for the skintone picker it becomes completely unusable on old iOS in LTR because it appears on the left instead of on the right.
=> fix: support RTL direction

.github/workflows/benchmarks.yml, src/database/databaseLifecycle.js, src/database/idbInterface.js, src/database/idbUtil.js, test/benchmark/benchmark.js, test/benchmark/database-interactions.html, test/benchmark/database-interactions.tachometer.json
Modified version of https://github.com/nolanlawson/emoji-picker-element/pull/165.
This time I added a benchmark to actually try to suss out the performance improvement. It's there, but it only seems to appear when using lots of database operations.
`transaction.commit()` improves perf a little, relaxed durability improves a lot.
=> perf: use relaxed IDB transactions and manually commit

README.md
I'm guessing that https://github.com/nolanlawson/emoji-picker-element/issues/231 is caused by something going wrong in the iframe, since there are occasional browser issues with using canvas in an iframe. If we switch from CodePen to an iframe-less demo site, then there should be fewer issues.
=> docs: use bl.ocks for the React demo

README.md
Fixes #233
As it turns out, you can totally use Twemoji with `emoji-picker-element`. I wouldn't really recommend it because of the perf cost, but you can do it.
Adds a link to [a demo ](https://bl.ocks.org/nolanlawson/fead700a0325aabd92670d56d6d422d8)showing how to do this.
=> docs: add demo of using Twemoji

README.md
Somewhat addresses #269
Add a link to [a demo](https://bl.ocks.org/nolanlawson/raw/1c67a41fb24978bab93a44ed1d62fab2/) of how to detect missing flag emoji on Windows and fall back to Twemoji in that case.
=> docs: add link to demo for Windows flag fallback

src/picker/constants.js
Previous discussion: https://github.com/nolanlawson/emoji-picker-element/pull/268#issuecomment-1073347283
On Windows and Linux (but apparently not MacOS or Android), Firefox ships its own `"Twemoji Mozilla"` font. On Windows in particular, the conflicts with the existing Segoe UI font, causing several issues:
- Older emoji render in Segoe, newer emoji render in Twemoji
- Transgender flag renders as double emoji
- England, Scotland, and Wales flags render as black flags
This PR changes the order of fonts in the `font-family` list to put `"Twemoji Mozilla"` first. I'm just going to assume that, if Mozilla is bundling their own font in the browser, then they know what they're doing and they're shipping emoji updates faster than the underlying OS.
This assumption will break if the underlying …
=> fix: newer emoji and flags on Firefox on Windows

src/picker/components/Picker/Picker.html
I added this in #19. After reading [a bit more](https://tink.uk/using-the-aria-owns-attribute/) about `aria-owns`, and now that aXe is no longer warning about this, I don't think this is necessary. There is no difference in NVDA or VoiceOver when adding this, and I think semantically it's wrong anyhow. (The listbox can't be a child of the input… I think I was confused because in [the ARIA combobox example](https://www.w3.org/TR/wai-aria-practices-1.1/examples/combobox/aria1.1pattern/listbox-combo.html) the combobox wrapper `aria-own`s the listbox, but in the notes they say that that's just to place the listbox directly after the input (which is also a child of the wrapper). I'm not too concerned about the ordering being off (because you're not meant to tab to the search results anyway; …
=> fix: remove aria-owns

bin/bundlesize.js, package.json, yarn.lock
bundlesize doesn't seem actively maintained, we can just write our own script.
=> chore: remove bundlesize package, use our own script

rollup.config.js
This reduces the bundle size a small amount, even if it's not much.
=> perf: trim unused svelte options

src/picker/components/Picker/Picker.js, src/picker/utils/resetScrollTopIfPossible.js
Moving to a function outside of the Svelte component avoids Svelte adding invalidations
=> fix: simpler solution to avoid svelte invalidations

src/picker/i18n/pl.js
=> chore: added polish translation file

src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js, test/spec/picker/Picker.test.js, test/spec/picker/shared.js
Fixes #335
After upgrading Svelte, I noticed a new accessibility [warning](https://github.com/sveltejs/svelte/blob/3bc791b/site/content/docs/06-accessibility-warnings.md#a11y-aria-activedescendant-has-tabindex) about how `activedescendant` elements should have `tabindex`. I looked into it, and decided I could simplify the skintone picker by abiding by this rule.
Tested in various screenreaders/browsers, the behavior is the same as before, but I was able to clean up the code a bit and get rid of the warning. I also went ahead and fixed #335 because I noticed it.
- NVDA+Firefox
- NVDA+Chrome
- VoiceOver+Safari
- VoiceOver+Chrome
=> fix: simplify skintone listbox

package.json, yarn.lock
Rather than #353, we should just downgrade conventional-changelog-cli for now... the new behavior is not great. We can figure out later why something broke in 3.0.0.
=> chore: downgrade conventional-changelog-cli for now

bin/bundlesize.js, src/picker/components/Picker/Picker.html, src/picker/components/Picker/Picker.js, src/picker/utils/summarizeEmojisForUI.js, test/spec/picker/custom.test.js, test/spec/picker/dataSource.test.js
Fixes #366
The `title` now comes from the `annotation` (if available - custom emoji may not have these). If not, it falls back to the shortcodes separated by a comma.
I also added the `annotation` to the `aria-label` because it seems like a nice enhancement – the annotation is often a better description than the shortcodes.
I don't see a reason to remove the shortcodes from the `aria-label` – it's just additional information, and the screenreader user can tab to the next emoji if they don't want to hear the shortcodes listed.
One downside of this is that there is no way for a sighted mouse user to figure out the shortcodes, but this is not vital to me since sighted mobile users were never able to see the `title` anyway.
=> fix: put annotation in title/aria-label

package.json, test/storage/test.js, yarn.lock
Guess WebKit changed where IDB data is stored.
=> chore: fix storage tests in webkit

rollup.config.js, shims/svelte-v3-shim.js
Fixes #379
Avoids breaking old browsers by avoiding the optional chaining (`?.`) syntax.
=> fix: avoid newer JS syntax to support old Safari

README.md, bin/versionsAndTestEmoji.js, package.json, test/spec/database/custom.test.js, test/spec/database/favsAndSkinTone.test.js, yarn.lock
Adds support for [emoji v15.1](https://emojipedia.org/emoji-15.1) with 🐦‍🔥 (phoenix) and 🙂‍↔️ (shaking head) among others.
See also https://github.com/nolanlawson/emoji-picker-element-data/pull/8
=> feat: add support for emoji v15.1

src/picker/constants.js
=> fix: use correct "red heart" in default favorites

test/benchmark/benchmark.js, test/benchmark/change-tab.benchmark.js, test/benchmark/search.benchmark.js, test/benchmark/utils.js
Messed up #389 a bit, should wait for the picker to fully load before running any benchmarks.
=> perf: wait for initial load in benchmarks

src/picker/components/Picker/Picker.js
I don't believe this will help with #398, but it can't hurt. I realized that we don't actually need to call `getRootNode` at all, because the `shadowRoot` never changes.
=> fix: avoid calling getRootNode

test/spec/database/Database.test.js, test/spec/database/getEmojiBySearchQuery.test.js, test/spec/database/getEmojiByShortcode.test.js, test/spec/database/getEmojiByUnicode.test.js, test/spec/database/offlineFirst.test.js, test/spec/database/secondLoad.test.js, test/spec/mockFetch.js, test/spec/picker/element.test.js, test/spec/picker/errors.test.js, test/spec/picker/favorites.test.js, test/spec/shared.js
This is just a refactor of the fetch mocking in the test code so that it's easier to set a universal delay.
It also includes a code comment about an apparent race condition, see #407.
=> test: centralize fetch mocks in one place

src/picker/utils/calculateTextWidth.js
#418 makes me a bit nervous but I can't seem to find any case in the Vitest tests at least where the `node` would be undefined... this adds a check to prove it.
=> test: add test to ensure that node is defined

README.md, package.json, pnpm-lock.yaml, test/adhoc/index.html
All browsers support this now, the polyfill can be de-emphasized.
=> chore: remove focus-visible polyfill from local dev server

bin/setupTachometerConfigs.js, package.json, pnpm-lock.yaml, test/benchmark/benchmark.js, test/benchmark/change-tab.benchmark.js, test/benchmark/database-interactions.benchmark.js, test/benchmark/first-load.benchmark.js, test/benchmark/search.benchmark.js, test/benchmark/second-load.benchmark.js, test/benchmark/utils.js
it looks like I've been using Tachometer incorrectly for some time, and wasn't actually comparing PRs against the master branch. :sweat_smile: 
Due to https://github.com/google/tachometer/issues/215 I need to make sure that any time we import the Picker/Database from a benchmark script, we do so from an npm package name that Tachometer can swap out. Luckily we can just create a dummy `file:.` dependency to do exactly this.
Without this PR, the local and "remote" versions of Tachometer are both the same – just the local code!
=> chore: fix tachometer package swapping

.github/workflows/benchmarks.yml, package.json
Follow-up to #439 
Unfortunately, since I can't figure out how to get `PERF=1` mode running when Tachometer builds the remote branch, we should just disable it everywhere. It gives additional instrumentation, which may distort the benchmark since we're not technically comparing apples to apples. The downside is that it's harder to debug the benchmarks, but it's better to have accurate benchmarks than debuggable ones (for now).
=> chore: run benchmarks in non-PERF mode

src/picker/components/Picker/Picker.js, src/picker/components/Picker/reactivity.js, src/picker/utils/checkZwjSupport.js, test/spec/picker/zwjEmoji.test.js
This is an experiment where we avoid additional re-renders by 1) not forcing an update to the `state` is object equality is still the same, and 2) avoiding an extra re-render if the browser supports all ZWJ-containing emoji.
Probably needs a battery of tests before it can be merged, but opening the PR anyway.
=> perf: avoid unnecessary re-renders

src/picker/utils/testColorEmojiSupported.js
This improves the perf of determining the emoji support level, although to see the difference you have to run Chrome in headful mode (interestingly).
```
second-load
┌─────────────┬───────────┐
│     Browser │ chrome    │
│             │ 127.0.0.0 │
├─────────────┼───────────┤
│ Sample size │ 100       │
└─────────────┴───────────┘
┌─────────────┬─────────────┬────────────┬─────────────────────┬───────────────────┬───────────────────┐
│ Benchmark   │ Version     │ Bytes      │            Avg time │    vs this-change │    vs tip-of-tree │
│             │             │            │                     │                   │       tip-of-tree │
├─────────────┼─────────────┼────────────┼─────────────────────┼───────────────────┼───────────────────┤
│ this-change │ <none>      │ 860.51 KiB │ …
```
=> perf: use `willReadFrequently`

.github/workflows/benchmarks.yml, src/picker/components/Picker/PickerTemplate.js, src/picker/styles/picker.scss, test/benchmark/benchmark.js, test/benchmark/many-custom-emoji.benchmark.js
Rather than using list virtualization (which has accessibility and complexity issues), we can use [`content-visibility`](https://web.dev/articles/content-visibility#skipping_rendering_work_with_content-visibility) to hide offscreen categories of custom emoji. This should significantly reduce layout costs, at least in browsers that support `content-visibility` (Safari has it in Tech Preview only).
Helps with #444 a lot, although there is probably more work we can do.
=> perf: use `content-visibility` for custom emoji

src/picker/components/Picker/Picker.js
This won't show up in the benchmarks, but we do an extra recalculation of the custom emoji search index that we don't need to.
=> perf: avoid recalculating custom emoji index

src/database/customEmojiIndex.js
Optimize the `trie` function which is used heavily when setting `customEmoji`.
=> perf: optimize trie construction

bin/bundlesize.js, package.json, src/picker/components/Picker/Picker.js, src/picker/components/Picker/PickerTemplate.js, src/picker/styles/picker.scss, src/picker/utils/contentVisibilityAction.js, src/picker/utils/intersectionObserverAction.js, test/adhoc/index.html
This is a variation on #449 but with a few tweaks:
- Instead of rendering an `<img>` at all, we use `background-image`. This reduces the total number of elements needed to render 20k emojis by half (20k instead of 40k)
- Use ~~`contentvisibilityautostatechange`~~ `IntersectionObserver` to toggle a CSS class which controls whether the background image is shown or not. This simulates what `<img loading=lazy>` was doing for us but without an `<img>`.
=> perf: use `background-image` instead of `<img>`

src/picker/components/Picker/PickerTemplate.js, test/spec/picker/favorites.test.js
Random dumb bug I noticed – the favorites should not have their `aria-selected` rendered at all, even if something is selected in the main panel.
=> fix: fix favorites `aria-selected` rendering

src/picker/components/Picker/PickerTemplate.js, src/picker/styles/picker.scss
Fixes #453. Had to get a bit creative here, but the perf optimization is preserved and Firefox is no longer rendering the double emoji.
=> fix: fix firefox double emoji

src/picker/components/Picker/Picker.js, src/picker/utils/resetScrollTopIfPossible.js
Another dumb bug that snuck in at some point (probably #437). If all ZWJ emoji are supported, then we don't re-render and thus never reset the `scrollTop`. This fixes that.
Repro:
1. Scroll down
2. Click to another tab
3. We should be scrolled to the top now
=> fix: fix resetting `scrollTop`

src/picker/styles/picker.scss
Might be a perf improvement, let's see.
=> perf: do not render offscreen pseudo at all

src/picker/components/Picker/PickerTemplate.js, src/picker/components/Picker/framework.js, test/spec/picker/framework.test.js
We could accidentally render the string `undefined` in some cases which would be wrong. Might as well guard against it.
=> fix: avoid undefined/null expression values

README.md, bin/versionsAndTestEmoji.js, package.json, pnpm-lock.yaml, test/spec/database/Database.test.js, test/spec/database/custom.test.js, test/spec/database/getEmojiBySearchQuery.test.js, test/spec/picker/Picker.test.js, test/spec/picker/favorites.test.js, test/spec/picker/scrolling.test.js
See: 
- https://github.com/milesj/emojibase/pull/180
- https://github.com/nolanlawson/emoji-picker-element-data/pull/13
=> feat: emoji v16.0

.github/workflows/tests.yml
The memory leak tests are now giving this error due to Puppeteer running in Ubuntu 24.04:
```
Error: Failed to launch the browser process!
[3197:3197:1214/235227.041856:FATAL:zygote_host_impl_linux.cc(128)] No usable sandbox! If you are running on Ubuntu 23.10+ or another Linux distro that has disabled unprivileged user namespaces with AppArmor, see https://chromium.googlesource.com/chromium/src/+/main/docs/security/apparmor-userns-restrictions.md. Otherwise see https://chromium.googlesource.com/chromium/src/+/main/docs/linux/suid_sandbox_development.md for more information on developing with the (older) SUID sandbox. If you want to live dangerously and need an immediate workaround, you can try using --no-sandbox.
[1214/235227.049018:ERROR:file_io_posix.cc(145)] open …
```
=> chore(ci): use ubuntu 22.04 for now

README.md
There is an error in the readme - incorrectly stating that the cross-origin server has to provide Access-Control-Allow-Headers, where the header we want is  [Access-Control-Expose-Headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers)
> The HTTP Access-Control-Expose-Headers [response header](https://developer.mozilla.org/en-US/docs/Glossary/Response_header) allows a server to indicate which response headers should be **made available to scripts** running in the browser in response to a cross-origin request.
I've also deleted the now-obsolete info about Safari not supporting the header
Best regards,
ympek
=> fix: change Access-Control-Allow-Headers to Access-Control-Expose-Headers in the readme

database.d.ts, index.d.ts, picker.d.ts, trimEmojiData.d.ts
In TypeScript projects using `moduleResolution: node16`, emoji-picker-element's types aren't interpreted correctly. The problem is that the types are using extensionless relative imports, and extensions are required with node16 moduleResolution.
Since it appears the types are hand-authored, the fix is straightforward - add the .js extension to the imports in the types file. I have confirmed that this change makes this package usable in TypeScript projects with moduleResolution: node16, and in general bundlers handle both forms so it shouldn't matter to other uses.
There is a lot more information about why things work this way at <https://www.typescriptlang.org/docs/handbook/modules/theory.html#typescript-imitates-the-hosts-module-resolution-but-with-types> but the short version is that …
=> Add js extensions to imports in type definitions

README.md, custom-elements.json, docs/index.html, shared.d.ts, src/picker/components/Picker/Picker.js, test/spec/picker/Picker.test.js
Fixes #281
I really don't like adding additional API surface just to work around a Safari bug, but even if WebKit fixes it tomorrow, there will be old versions of Safari floating around for ages. 
Adds a new event, `emoji-click-sync`, which does the same thing as `emoji-click` but is synchronous and its `event.detail` is a promise for the same `detail` object in the non-sync version.
=> feat: add `emoji-click-sync` event as Safari workaround

package.json, pnpm-lock.yaml, src/database/databaseLifecycle.js, test/spec/database/Database.test.js
This is just basically to increase our test coverage and to take advantage of a new fake-indexeddb feature: https://github.com/dumbmatter/fakeIndexedDB/pull/126
=> test: test abnormal IndexedDB close event
