nolanlawson/emoji-picker-element

config/jest.setup.js

Should make tests easier to write in the future

test: use fresh IDB for every test

---

src/database/databaseLifecycle.js
src/database/migrations.js

perf: reduce idb migration code

---

package.json
src/picker/components/Picker/Picker.js
test/spec/picker/Picker.test.js

feat: add Home/End keyboard shortcuts

---

CHANGELOG.md
package.json
yarn.lock

Adds a nice CHANGELOG.md, seems convenient.

chore: add conventional-changelog-cli

---

README.md

docs: add note about emojibase-data v5 to docs

---

docs/index.html

Chrome Beta supports this now, no reason to apply it everywhere.

docs: conditionally apply :focus-visible polyfill

---

.travis.yml

1. be explicit
1. in chronological order
1. uniform formatting
https://github.com/szepeviktor/emoji-picker-element/blob/patch-1/.travis.yml

chore: enhance TravisCI config

---

src/types/picker.ts

docs: add removeEventListener

---

package.json
yarn.lock

forgot I used this in dev mode

test: re-add focus-visible polyfill for adhoc tests

---

README.md
src/database/constants.js
src/types/database.ts
src/types/picker.ts

fix: use @^ for versions

---

src/database/Database.js
src/database/utils/trie.js
src/picker/utils/emojiSupport.js
src/picker/utils/requestIdleCallback.js
test/spec/database/Database.test.js
test/spec/picker/skinTones.test.js

Trying to get coverage close to 100%

test: improve test coverage

---

src/picker/components/Picker/Picker.html
src/picker/components/Picker/Picker.js
src/picker/components/Picker/Picker.scss
src/picker/styles/global.scss
src/picker/styles/resets.scss

Just some minor cleanup that results in a smaller bundle size.

perf: reduce bundle size by optimizing HTML/CSS a bit

---

test/spec/picker/Picker.test.js
test/spec/picker/dataSource.test.js
test/spec/picker/shared.js
test/spec/shared.js

Improves test coverage by testing for emoji with array skin tones (i.e. multiple tones).

test: add test for array skin tones

---

.circleci/config.yml
jest.config.cjs

It makes me less nervous to have strict code coverage requirements in place, even if in practice it's really hard for certain files (Picker.svelte).

test: test code coverage in CI

---

jest.config.cjs
src/picker/components/Picker/Picker.html
src/picker/components/Picker/Picker.js
src/shared/log.js
test/spec/picker/errors.test.js

Code had to be refactored a bit to make this possible, and I had to add some kind-of-pointless `console.error()` messages to deal with unhandled promise rejections, but this shouldn't be a huge change.

refactor: refactor and properly test offline mode

---

jest.config.cjs
src/picker/components/Picker/Picker.js

Ignore more code for code coverage

test: ignore more code that jest cannot test

---

src/database/idbInterface.js

chore: add perf marks for committing initial IDB data

---

src/picker/utils/determineEmojiSupportLevel.js
src/picker/utils/testColorEmojiSupported.js

fixes #132
On canvas error, just guess the latest emoji version rather than showing an error.

fix: guess latest emoji version on canvas error

---

package.json
rollup.config.js

perf: reduce bundle size

---

test/memory/test.js

It wasn't giving accurate results, this fixes it.

test: fix memory test

---

.github/workflows/benchmarks.yml
.gitignore
CONTRIBUTING.md
bin/run-benchmark.sh
bin/setup-benchmark.sh
package.json
test/benchmark/benchmark.js
test/benchmark/first-load.html
test/benchmark/first-load.tachometer.json
test/benchmark/package.json
test/benchmark/second-load.html
test/benchmark/second-load.tachometer.json
yarn.lock

Not sure how helpful/reliable this will be, but worth playing around with...

test: add performance benchmarks using tachometer

---

.circleci/config.yml
package.json

Make the CI tests faster by avoiding stuff we don't need to do.

test: make CI tests more efficient

---

.github/workflows/bundlesize.yml

test: add compressed-size-action

---

src/picker/components/Picker/Picker.js
test/spec/picker/Picker.test.js

fix: Esc key dismisses listbox

---

src/picker/components/Picker/Picker.js
src/picker/constants.js
test/spec/picker/attributes.test.js
test/spec/picker/custom.test.js

test: add tests for attributes/props

---

package.json
src/picker/PickerElement.js
test/spec/picker/errors.test.js

It was always supposed to be read-only; I just didn't get around to doing this.

fix: make database read-only

---

src/picker/components/Picker/Picker.html
src/picker/components/Picker/Picker.js
test/spec/picker/Picker.test.js
test/spec/picker/custom.test.js

fix: render custom category if only one exists

---

test/spec/picker/element.test.js
test/spec/picker/errors.test.js
test/spec/picker/lifecycle.test.js

Make them less dependent on implementation details.

test: make tests more resilient

---

test/spec/picker/scrolling.test.js

This test would have caught the bug identified in https://github.com/nolanlawson/emoji-picker-element/pull/180

test: add scroll test

---

src/picker/components/Picker/Picker.js

fix: remove Svelte assignment invalidation

---

src/picker/components/Picker/Picker.js

A more succinct way of doing #182

refactor: terser way to avoid invalidations

---

src/picker/PickerElement.js
test/spec/picker/upgrade.test.js

fix: fix setting props before element upgrade

---

bin/buildStylesForJest.js
config/jest.setup.js
package.json
rollup.config.js
src/picker/PickerElement.js
test/spec/picker/Picker.test.js
yarn.lock

Not actually doing anything with this right now, but seems worth testing.

test: inject actual styles in jest

---

README.md

Explains how to optimize the CSS for small screens. Related to #206

docs: add docs on CSS for small screens

---

README.md
src/picker/i18n/ar.js
src/picker/i18n/de.js
src/picker/i18n/en.js
src/picker/i18n/es.js
src/picker/i18n/fr.js
src/picker/i18n/pt_BR.js
src/picker/i18n/pt_PT.js
src/picker/i18n/tr.js

Fixes #216
Adds the new languages, and removes the "try refreshing" part from the network error text so that the translations are all consistent.

feat: add new translations

---

src/database/Database.js
test/spec/picker/lifecycle.test.js

Fixes #225
I'm solving this in kind of a clunky way, but it works.

fix: fix db undefined when adding/removing element

---

src/picker/i18n/ms_MY.js

We added Malaysian to our app so here are the strings for emoji-picker.

Added ms_MY.js (Malaysian text)

---

README.md
bin/versionsAndTestEmoji.js
package.json
src/database/utils/extractTokens.js
test/spec/database/Database.test.js
test/spec/picker/Picker.test.js
test/spec/shared.js
yarn.lock

Fixes #236
Related: https://github.com/nolanlawson/emoji-picker-element-data/pull/3

feat: update to emoji 14.0

---

src/picker/PickerElement.js

fix: customElements.define called twice

---

src/picker/i18n/nl.js

I added the Dutch translation file.

Added Dutch translation file

---

src/picker/components/Picker/Picker.js
test/spec/picker/custom.test.js

fix: fix category when unsetting customEmoji

---

src/picker/styles/variables.scss

fix: used dark colors for scrollbar in dark mode

---

src/picker/i18n/ru_RU.js

This Russian translation is generously provided by @vorons https://github.com/nolanlawson/pinafore/pull/2219#issuecomment-1322968623

feat: add ru_RU locale

---

README.md
docs/demos/flags/index.html
docs/demos/input/index.html
docs/demos/react/index.html
docs/demos/tooltip/index.html
docs/demos/twemoji/index.html

Move demos to this repo because it looks like `bl.ocks.org` is :skull:

docs: move demos to this repo

---

README.md
docs/demos/react/index.html
docs/demos/tooltip/index.html

Messed this up in the previous PR

docs: fix links to demos

---

docs/demos/tooltip/index.html

Nothing against unpkg, but I want fewer deps in these demos

docs: remove unpkg from demos

---

docs/demos/twemoji-mozilla/index.html

Fix a cache issue with jsdelivr

docs: fix demo

---

README.md
bin/versionsAndTestEmoji.js
package.json
yarn.lock

feat: add support for emoji v15

---

src/database/utils/cleanEmoji.js

fix: make "People and body" category work in Firefox content script

---

src/database/utils/cleanEmoji.js

Small optimization on top of #357

perf: hoist global check

---

README.md

Better docs to help common SSR errors like in https://github.com/nolanlawson/emoji-picker-element/issues/371

docs: add docs on usage in meta-frameworks

---

src/picker/i18n/fr.js

Hello there! I just wanted to suggest a French translations update :)

💬 French translations

---

src/database/utils/requiredKeys.js
src/database/utils/transformEmojiData.js
src/trimEmojiData.js
test/spec/database/Database.test.js
test/spec/shared.js

Fix for https://github.com/nolanlawson/emoji-picker-element-data/issues/12

fix: allow for emoji with no tags

---

bin/setupTachometerConfigs.js

Allow using env vars to set the browser, conditions, etc.

chore: allow for configuring tachometer

---

src/picker/components/Picker/framework.js

This is like a 1% perf improvement in Firefox and 1-10% in Chrome for the `many-custom-emoji` benchmark, so seems worthwhile.
```
┌─────────────┬──────────────────┐
│     Browser │ firefox-headless │
│             │ 130.0            │
├─────────────┼──────────────────┤
│ Sample size │ 1990             │
└─────────────┴──────────────────┘
┌─────────────┬─────────────┬─────────────┬─────────────────────┬─────────────────┬─────────────────┐
│ Benchmark   │ Version     │ Bytes       │            Avg time │  vs this-change │  vs tip-of-tree │
│             │             │             │                     │                 │     tip-of-tree │
├─────────────┼─────────────┼─────────────┼─────────────────────┼─────────────────┼─────────────────┤
│ this-change │ <none>      │ 1027.21 KiB │ …
```

perf: optimize DOM traversal

---

test/spec/picker/framework.test.js

test: add test for previous optimization

---

package.json
pnpm-lock.yaml
src/picker/styles/variables.scss

Hard-codes some colors to avoid changes in the output `picker.js` to CSS colors: https://github.com/sass/dart-sass/blob/main/CHANGELOG.md#1790

chore: update sass

---

package.json
pnpm-lock.yaml
src/picker/styles/global.scss
src/picker/styles/picker.scss

`@import` is deprecated: https://sass-lang.com/blog/import-is-deprecated/

chore: update deps and remove sass `@import`

---

src/picker/i18n/fa.js

Hello All,
I have added Persian Language.
Let me know if there is other things we should do to add Persian language support to the emoji picker.
Regards,
Ali

Internationalization: add Persian Language in i18n

---

src/picker/i18n/ja.js

Hi,
I would like to add some default translations for Japanese 🙇

feat: add Japanese language support in i18n
